jobs:
  - job: Linux
    pool:
      vmImage: "ubuntu 16.04"
    steps:
      - template: ci-steps.yml

  - job: Windows
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - template: ci-steps.yml

  - job: mcOS
    pool:
      vmImage: "macOS-10.13"
    steps:
      - template: ci-steps.yml
